

//Adding new transaction
POST http://localhost:3000/transactions/
Content-Type: application/json

{
    "type": "income",
    "category": "Salary",
    "amount": 5000,
    "date": "2024-10-22",
    "description": "October salary"
}

###

//Retrieve all transactions
GET http://localhost:3000/transactions/

###

//Retrieve a transaction by ID
GET http://localhost:3000/transactions/1

###

//Update a transaction by ID
PUT http://localhost:3000/transactions/3
Content-Type: application/json

{
    "type": "expense",
    "category": "Groceries",
    "amount": 200,
    "date": "2024-10-21",
    "description": "Weekly groceries"
}

###

//Delete a transaction by ID
DELETE http://localhost:3000/transactions/2

###

//Retrieve a summary of transactions (total income, expenses, and balance)
GET http://localhost:3000/summary

###

GET http://localhost:3000/report?month=10&year=2024
